# nixpacks.toml - System dependencies for Railway (MediaPipe only)
[phases.setup]
nixPkgs = [
  "pkg-config"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:${PORT:-5000} --workers 1 --timeout 120 --preload --log-level info"
