# nixpacks.toml - System dependencies for Railway
[phases.setup]
nixPkgs = [
  "cmake",
  "gcc",
  "gfortran",
  "libopenblas",
  "pkg-config"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install cmake",
  "pip install dlib==19.24.1 --verbose",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload --log-level info"
