# nixpacks.toml - System dependencies for OpenCV/MediaPipe
[phases.setup]
nixPkgs = [
  "libGL",
  "libglib", 
  "glib",
  "mesa",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender"
]

[variables]
PYTHONPATH = "/app"
DISPLAY = ":99"
